apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    meta.helm.sh/release-name:  {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: traefik
  tls:
    # TODO
    - hosts:
        - prometheus.neikoscloud.net
      secretName: prometheus-tls
  rules:
    - host: prometheus.neikoscloud.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prometheus-kube-prometheus-prometheus
                port:
                  number: 9090