apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.clusterSecretStore.name | default "aws-secrets-manager" }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.aws.region | default "us-east-1" }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.aws.serviceAccountName | default "external-secrets" }}
            namespace: {{ .Values.aws.serviceAccountNamespace | default "external-secrets" }}