apiVersion: v2
name: external-secrets
description: A external-secrets Helm chart for Kubernetes
type: application
version: 1.0.0
appVersion: "1.0"
dependencies:
  - name: external-secrets
    repository: https://charts.external-secrets.io
    version: 0.14.1