# Configuration for custom ClusterSecretStore template
clusterSecretStore:
  name: aws-secrets-manager
  region: us-east-1
  serviceAccount:
    name: external-secrets
    namespace: external-secrets

# Configuration for external-secrets dependency chart
external-secrets:
  installCRDs: true
  serviceAccount:
    create: true
    name: external-secrets
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::459063349398:role/ExternalSecretsRole
  # Ensure the webhook also uses the same service account
  webhook:
    serviceAccount:
      create: false
      name: external-secrets
  certController:
    serviceAccount:
      create: false
      name: external-secrets
