apiVersion: v2
name: jenkins
description: A Helm chart for Kubernetes to deploy Jenkins
type: application
version: 1.0.0
appVersion: "1.0"
dependencies:
  - name: jenkins 
    # condition: jenkins.enabled
    repository: https://charts.jenkins.io
    version: "5.8.3"