replicaCount: 1

image:
  repository: ghcr.io/mlflow/mlflow
  tag: "v2.17.2"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: true
  className: traefik
  hosts:
    - host: mlflow.neikoscloud.net
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: mlflow-tls
      hosts:
        - mlflow.neikoscloud.net

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 1
    memory: 1Gi

backendStore:
  type: postgresql
  host: postgres-mlflow-postgresql
  port: 5432
  database: mlflow
  username: mlflow
  password: mlflow123

artifactStore:
  s3:
    endpoint: https://minio.neikoscloud.net
    bucket: mlflow
    accessKey: admin
    secretKey: admin123
    insecure: true

persistence:
  enabled: true
  size: 8Gi
  storageClass: gp2
