apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.minio.secretName }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{ .Values.minio.accessKeyName }}: admin
  {{ .Values.minio.secretKeyName }}: admin123
