apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-aws-credentials
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: {{ .Release.Name }}-aws-credentials
    creationPolicy: Owner
  data:
    - secretKey: awsAccessKey
      remoteRef:
        key: "jenkins/aws/access"
        property: aws_access_key
    - secretKey: awsSecretKey
      remoteRef:
        key: "jenkins/aws/access"
        property: aws_secret_key
