apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-docker-registry
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: {{ .Values.imagePullSecrets.name }}
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "{{ .Values.imagePullSecrets.registry }}": {
                "username": "{{ `{{ .username }}` }}",
                "password": "{{ `{{ .password }}` }}",
                "auth": "{{ `{{ printf "%s:%s" .username .password | b64enc }}` }}"
              }
            }
          }
  data:
    - secretKey: username
      remoteRef:
        key: "fastapi/docker/registry"
        property: username
    - secretKey: password
      remoteRef:
        key: "fastapi/docker/registry"
        property: password
