# Disable CRD creation - install manually to avoid annotation size issue
kube-prometheus-stack:
  crds:
    enabled: false

prometheus:
  configmapReload:
    prometheus:
      containerPort: 8080
  server:
    # baseURL: "/prometheus"
    # prefixURL: "/prometheus"
    extraFlags:
      - web.enable-lifecycle

  extraScrapeConfigs: |
    - job_name: 'jenkins-prod'
      metrics_path: '/jenkins/prometheus'

      static_configs:
        - targets: ['jenkins-prod.jenkins-prod:8080']