apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  destination:
    namespace: traefik
    name: in-cluster
  project: default
  source:
    path: charts/traefik
    repoURL: https://github.com/DarkinSideNet/DevOps_Projects.git
    targetRevision: main
    helm:
      releaseName: traefik
      valueFiles:
        - values-prod.yaml
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    # no auto-synch for prod
    # automated: