{{- if and .Values.externalSecrets.enabled .Values.externalSecrets.github.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecrets.github.secretName }}
  namespace: argocd
  labels:
    app: argocd
    managed-by: helm
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: {{ .Values.externalSecrets.github.secretName }}
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.externalSecrets.github.secretKey }}
      remoteRef:
        key: {{ .Values.externalSecrets.github.secretPath }}
        property: {{ .Values.externalSecrets.github.secretKey }}
{{- end }}
