{{- if .Values.externalSecrets.sshEks.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jenkins-ssh-eks-credential
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: jenkins-ssh-eks-credential
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: {{ .Values.externalSecrets.sshEks.secretPath }}
        property: username
    - secretKey: privateKey
      remoteRef:
        key: {{ .Values.externalSecrets.sshEks.secretPath }}
        property: privateKey
{{- end }}
