{{- if .Values.externalSecrets.default.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jenkins-server
  namespace: {{ .Release.Namespace }}
  labels:
    app: jenkins
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: jenkins-server
    creationPolicy: Owner
  data:
    - secretKey: jenkins-admin-user
      remoteRef:
        key: {{ .Values.externalSecrets.default.secretPath }}
        property: id

    - secretKey: jenkins-admin-password
      remoteRef:
        key: {{ .Values.externalSecrets.default.secretPath }}
        property: password
{{- end }}
