jenkins:
  controller:
    # Sửa đoạn này
    image:
      repository: "jenkins/jenkins" # Tên image nằm ở đây
      tag: "lts-jdk21"              # Tag nằm trong block image
      
    # ... các cấu hình resources, serviceType giữ nguyên ...
    resources:
      requests:
        cpu: "500m"
        memory: "1024Mi"
      limits:
        cpu: "1000m"
        memory: "2048Mi"
    serviceType: NodePort
    nodePort: 30000
    
    installLatestPlugins: false
    overwritePlugins: true
    installPlugins:
      - configuration-as-code:1963.v24e046127a_3f
      - git-client:6.4.1
      - git:5.6.0
      - workflow-aggregator:600.vb_57cdd26fdd7
      - kubernetes:4306.vc91e951ea_eb_d
      
    JCasC:
      defaultConfig: true
      configScripts:
        welcome-message: |
          jenkins:
            systemMessage: "Configured via Wrapper Chart"

  persistence:
    enabled: true
    size: "8Gi"
    storageClass: ""