---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sweet500-prometheus-prod
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    name: in-cluster
  project: sweet500
  source:
    path: charts/monitoring/prometheus
    repoURL: https://github.com/DarkinSideNet/DevOps_Projects.git
    targetRevision: main
    helm:
      releaseName: prometheus-prod
      valueFiles:
        - values-prod.yaml
  syncPolicy:
    syncOptions:
      - CreateNamespace=true