apiVersion: v2
name: argo-workflows
description: Argo Workflows - Workflow engine for Kubernetes
type: application
version: 0.1.0
appVersion: "3.5.0"
dependencies:
  - name: argo-workflows
    version: "0.41.3"
    repository: https://argoproj.github.io/argo-helm
