apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jenkins-staging-cert
  namespace: jenkins-staging
spec:
  secretName: jenkins-staging-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - jenkins-staging.neikoscloud.net